/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Preview: typeof import('./src/components/preview/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Scale: typeof import('./src/components/box/scale.vue')['default']
    Screen: typeof import('./src/components/screen/index.vue')['default']
    Upload: typeof import('./src/components/upload/index.vue')['default']
  }
}
